### ISSUE TITLE
Torrent Support - Part 2

### ISSUE THREAD

**Issue by SonarrBot** [Sonarr/Sonarr#468]
With our initial version of Torrents released we need a list of stuff that we want to implement.
This list only contains the items we want. (the old checklist contained everything)

See https://trello.com/c/MBXeXBqt/140-torrent-support for the old one

Desired Indexers
- [x] Generic TorrentRss
- [x] Generic TorzNab (Newznab-based)
- [ ] Generic gazelle provider (https://github.com/WhatCD/Gazelle)

Desired Clients
- [x] rTorrent/ruTorrent
- [x] qbittorrent
- [ ] put.io (https://github.com/Sonarr/Sonarr/issues/1972)
- [ ] Aria2 (https://github.com/Sonarr/Sonarr/issues/1374)

Desired Features
- [ ] Check for Stalled Torrents (https://github.com/Sonarr/Sonarr/issues/958)
- [ ] Specify Seed Ratio / Time per Indexer (https://github.com/Sonarr/Sonarr/issues/1854)
- [ ] Unrar during the import process (https://github.com/Sonarr/Sonarr/issues/784)
- [x] Favor Season packs over single Episodes
- [x] Allow Delay for Torrents so that Usenet is favored on rss feed
- [x] Manual search shows Seeders/Leechers
- [ ] Deluge Daemon instead of Web (https://github.com/Sonarr/Sonarr/issues/1971)
- [x] Minimum number of seeders before grabbing
- [x] Allow disabling of min-seed check
- [x] Number of seeds over size
- [ ] BTN - single episodes being removed

**Comment by subzero79** [comment]
Does this branch works by just changing branch in UI updates, or is necessary to build it from github?

**Comment by subzero79** [comment]
Anyway this is a pastebin for tiny-tiny RSS web application in json format. I use this as an rss catcher when my NAS is offline from another low power device. You can have as many entries as you want per feed.

Format available is json and atom, but the latest one is kinda of parsed like html

http://pastebin.com/d3qTCzhn (json)

http://pastebin.com/pkkyquzf (Atom)

**Comment by xelra** [comment]
Any progress on the per-indexer seedratio and -time feature? Pretty please?

Look, I even have this digital flower for you. :)

	  /-_-\
	 /  /  \
	/  /    \
	\  \    /
	 \__\__/
	    \\
	    -\\    ____
	      \\  /   /
	____   \\/___/
	\   \ -//
	 \___\//-
	    -//
	     \\
	     //
	    //-
	  -//
	  //
	  \\
	   \\

**Comment by testarea1** [comment]
Leaving a comment for put.io support

**Comment by xelra** [comment]
This should go together with explicit support for season packs. And per-indexer seedtime and -ratio should take into consideration whether it downloaded a season pack or a single episode.

**Comment by aggonzo326** [comment]
Would love to see support for qbitorrent!!!

**Comment by mepcotterell** [comment]
put.io, please

**Comment by HammyHavoc** [comment]
Would love to see put.io.

**Comment by jorgenbs** [comment]
+1 for put.io

**Comment by Fastjur** [comment]
Any updates on the stall detection and Seed ratio?

**Comment by hafifuyku** [comment]
Hello. Put.io PM here. Happy to help with anything you need. (Accounts for example.) Write to me at info@put.io and I'll set it up. Cheers.

**Comment by marklajer** [comment]
+1 for put.io

**Comment by s4pph1re** [comment]
Add Tixati client support for Sonarr.
I use Tixati for the last 2 years, after I 've tested too many other clients, because I find this to be the only one that covers my needs.

Thank you

**Comment by erylflynn** [comment]
I also would like Tixati support.  Until I started using Sonarr it was my only bit torrent client.  And now that I am stuck with others I remember why I moved to Tixati.

**Comment by geauxtig3rs** [comment]
Add a third request for Tixati.  

Lightweight, full featured and unobtrusive.

**Comment by markus101** [comment]
Tixati does not have an API, the only thing that will work is the blackhole support Sonarr already has.

**Comment by ammadz** [comment]
Put.io is still on the wishlist? thanks

**Comment by s4pph1re** [comment]
@markus101 are you sure about the Tixati API?
I'm asking because I found out that DuckieTV handles downloads with Tixati.

**Comment by markus101** [comment]
Yes, another dev looked at implementing better support in Sonarr, but ultimately it was just an offshoot of Torrent Blackhole. Looks like DuckieTV does screen scraping to get around that, but not something we'd do for the same reason we don't do it for indexers.

**Comment by oimctony** [comment]
It would be amazing to have Put.io !

**Comment by s0lolol** [comment]
Deluge Daemon instead of Web.
I wish I could +1 this harder.

**Comment by weirdcrap** [comment]
another +1 for Deluge Daemon! I can't have YaRSS2 plugin support for other sites I don't use through sonarr if I have to keep the WebUI enabled.

**Comment by bmcclure** [comment]
What about Offcloud? They're an incredibly affordable service comparable to put.io, except integrating with cloud storage providers, and supporting Usenet in addition to Bittorrent. It could be a 1-stop download client solution for Sonarr.

**Comment by LSL1337** [comment]
It's quite an old topic, but any plans on supporting deluge daemon, instead of webui?

**Comment by Taloth** [comment]
Plans yes, but it's not being worked on. Biggest issue is get a reliable ssl/tls raw connection on both windows _and_ linux/mono. So I kinda parked it so we can look at it again when we switch to .net core (if we do that).

**Comment by Gex2501** [comment]
I see put.io on the list, how is progress going with them? I've been using their service for years and find them to be fantastic.

**Comment by markus101** [comment]
GHIs are open for individual issues so they can be tracked properly.

**Comment by anshuman852** [comment]
any update on aria2?

**Comment by falahati** [comment]
If we add support for Aria2, we can also consider allowing direct download via leeching services. Quite useful when P2P connections are limited or outright blocked. At minimum adds another level of privacy instead of your IP being listed as a peer in the tracker.

Tons of API samples and documentation as well:
https://www.seedr.cc/pulse/api-doc/#get-file-hls-url
https://bitport.io/api
https://github.com/Offcloud/offcloud-api
https://github.com/mbagattini/furk-net-download-manager

There are some local sites as well. This one is in Persian and is quite cheap if you know how to pay for it. But I didn't found any API documentation.
https://www.mul.ir/

**Comment by anshuman852** [comment]
Any update on aria2?
